 
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account/components/SettingsWidget': RouteRecordInfo<'/account/components/SettingsWidget', '/account/components/SettingsWidget', Record<never, never>, Record<never, never>>,
    '/account/SettingsView': RouteRecordInfo<'/account/SettingsView', '/account/SettingsView', Record<never, never>, Record<never, never>>,
    '/admin/AdminUserRolesView': RouteRecordInfo<'/admin/AdminUserRolesView', '/admin/AdminUserRolesView', Record<never, never>, Record<never, never>>,
    '/admin/AnnouncementsView': RouteRecordInfo<'/admin/AnnouncementsView', '/admin/AnnouncementsView', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/DeleteUserDialog': RouteRecordInfo<'/admin/components/dialogs/DeleteUserDialog', '/admin/components/dialogs/DeleteUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/EditUserDialog': RouteRecordInfo<'/admin/components/dialogs/EditUserDialog', '/admin/components/dialogs/EditUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/UserDetailsDialog': RouteRecordInfo<'/admin/components/dialogs/UserDetailsDialog', '/admin/components/dialogs/UserDetailsDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/UserManagementTable': RouteRecordInfo<'/admin/components/UserManagementTable', '/admin/components/UserManagementTable', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AdminUserRolesDialog': RouteRecordInfo<'/admin/dialogs/AdminUserRolesDialog', '/admin/dialogs/AdminUserRolesDialog', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AnnouncementCreateEditDialog': RouteRecordInfo<'/admin/dialogs/AnnouncementCreateEditDialog', '/admin/dialogs/AnnouncementCreateEditDialog', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AnnouncementDeleteConfirmationDialog': RouteRecordInfo<'/admin/dialogs/AnnouncementDeleteConfirmationDialog', '/admin/dialogs/AnnouncementDeleteConfirmationDialog', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AnnouncementDetailDialog': RouteRecordInfo<'/admin/dialogs/AnnouncementDetailDialog', '/admin/dialogs/AnnouncementDetailDialog', Record<never, never>, Record<never, never>>,
    '/admin/UserManagementView': RouteRecordInfo<'/admin/UserManagementView', '/admin/UserManagementView', Record<never, never>, Record<never, never>>,
    '/Auth': RouteRecordInfo<'/Auth', '/Auth', Record<never, never>, Record<never, never>>,
    '/ForbiddenView': RouteRecordInfo<'/ForbiddenView', '/ForbiddenView', Record<never, never>, Record<never, never>>,
    '/hometab/HomeAnnouncements': RouteRecordInfo<'/hometab/HomeAnnouncements', '/hometab/HomeAnnouncements', Record<never, never>, Record<never, never>>,
    '/hometab/HomeLogs': RouteRecordInfo<'/hometab/HomeLogs', '/hometab/HomeLogs', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/student/dialogs/CameraDialog': RouteRecordInfo<'/student/dialogs/CameraDialog', '/student/dialogs/CameraDialog', Record<never, never>, Record<never, never>>,
    '/student/dialogs/EditAnswersDialog': RouteRecordInfo<'/student/dialogs/EditAnswersDialog', '/student/dialogs/EditAnswersDialog', Record<never, never>, Record<never, never>>,
    '/student/dialogs/ScoreResultDialog': RouteRecordInfo<'/student/dialogs/ScoreResultDialog', '/student/dialogs/ScoreResultDialog', Record<never, never>, Record<never, never>>,
    '/student/dialogs/SearchResultDialog': RouteRecordInfo<'/student/dialogs/SearchResultDialog', '/student/dialogs/SearchResultDialog', Record<never, never>, Record<never, never>>,
    '/student/dialogs/StudentDetailsDialog': RouteRecordInfo<'/student/dialogs/StudentDetailsDialog', '/student/dialogs/StudentDetailsDialog', Record<never, never>, Record<never, never>>,
    '/student/dialogs/UploadImageDialog': RouteRecordInfo<'/student/dialogs/UploadImageDialog', '/student/dialogs/UploadImageDialog', Record<never, never>, Record<never, never>>,
    '/student/StudentView': RouteRecordInfo<'/student/StudentView', '/student/StudentView', Record<never, never>, Record<never, never>>,
    '/teachertab/components/GraphWidget': RouteRecordInfo<'/teachertab/components/GraphWidget', '/teachertab/components/GraphWidget', Record<never, never>, Record<never, never>>,
    '/teachertab/components/QuizesListWIdget': RouteRecordInfo<'/teachertab/components/QuizesListWIdget', '/teachertab/components/QuizesListWIdget', Record<never, never>, Record<never, never>>,
    '/teachertab/components/TeacherAnswerKeyWidget': RouteRecordInfo<'/teachertab/components/TeacherAnswerKeyWidget', '/teachertab/components/TeacherAnswerKeyWidget', Record<never, never>, Record<never, never>>,
    '/teachertab/components/TeacherStudentsWidget': RouteRecordInfo<'/teachertab/components/TeacherStudentsWidget', '/teachertab/components/TeacherStudentsWidget', Record<never, never>, Record<never, never>>,
    '/teachertab/dialogs/answerkey/AnswerKeyForm': RouteRecordInfo<'/teachertab/dialogs/answerkey/AnswerKeyForm', '/teachertab/dialogs/answerkey/AnswerKeyForm', Record<never, never>, Record<never, never>>,
    '/teachertab/dialogs/answerkey/ImageCaptureUpload': RouteRecordInfo<'/teachertab/dialogs/answerkey/ImageCaptureUpload', '/teachertab/dialogs/answerkey/ImageCaptureUpload', Record<never, never>, Record<never, never>>,
    '/teachertab/dialogs/answerkey/ImageSourceSelection': RouteRecordInfo<'/teachertab/dialogs/answerkey/ImageSourceSelection', '/teachertab/dialogs/answerkey/ImageSourceSelection', Record<never, never>, Record<never, never>>,
    '/teachertab/dialogs/AnswerPreviewDialog': RouteRecordInfo<'/teachertab/dialogs/AnswerPreviewDialog', '/teachertab/dialogs/AnswerPreviewDialog', Record<never, never>, Record<never, never>>,
    '/teachertab/dialogs/CreateAnswerKeysDialog': RouteRecordInfo<'/teachertab/dialogs/CreateAnswerKeysDialog', '/teachertab/dialogs/CreateAnswerKeysDialog', Record<never, never>, Record<never, never>>,
    '/teachertab/dialogs/DeleteAnswerKeyDialog': RouteRecordInfo<'/teachertab/dialogs/DeleteAnswerKeyDialog', '/teachertab/dialogs/DeleteAnswerKeyDialog', Record<never, never>, Record<never, never>>,
    '/teachertab/dialogs/DeleteConfirmationDialog': RouteRecordInfo<'/teachertab/dialogs/DeleteConfirmationDialog', '/teachertab/dialogs/DeleteConfirmationDialog', Record<never, never>, Record<never, never>>,
    '/teachertab/dialogs/EditAnswerKeysDialog': RouteRecordInfo<'/teachertab/dialogs/EditAnswerKeysDialog', '/teachertab/dialogs/EditAnswerKeysDialog', Record<never, never>, Record<never, never>>,
    '/teachertab/dialogs/FullImageDialog': RouteRecordInfo<'/teachertab/dialogs/FullImageDialog', '/teachertab/dialogs/FullImageDialog', Record<never, never>, Record<never, never>>,
    '/teachertab/dialogs/home/QrDialog': RouteRecordInfo<'/teachertab/dialogs/home/QrDialog', '/teachertab/dialogs/home/QrDialog', Record<never, never>, Record<never, never>>,
    '/teachertab/dialogs/home/StudentListDialog': RouteRecordInfo<'/teachertab/dialogs/home/StudentListDialog', '/teachertab/dialogs/home/StudentListDialog', Record<never, never>, Record<never, never>>,
    '/teachertab/dialogs/home/TabFolder': RouteRecordInfo<'/teachertab/dialogs/home/TabFolder', '/teachertab/dialogs/home/TabFolder', Record<never, never>, Record<never, never>>,
    '/teachertab/dialogs/ViewAnswerDialog': RouteRecordInfo<'/teachertab/dialogs/ViewAnswerDialog', '/teachertab/dialogs/ViewAnswerDialog', Record<never, never>, Record<never, never>>,
    '/teachertab/dialogs/ViewQrCodeDialog': RouteRecordInfo<'/teachertab/dialogs/ViewQrCodeDialog', '/teachertab/dialogs/ViewQrCodeDialog', Record<never, never>, Record<never, never>>,
    '/teachertab/TeacherAnswerKeyView': RouteRecordInfo<'/teachertab/TeacherAnswerKeyView', '/teachertab/TeacherAnswerKeyView', Record<never, never>, Record<never, never>>,
    '/teachertab/TeacherStudentsView': RouteRecordInfo<'/teachertab/TeacherStudentsView', '/teachertab/TeacherStudentsView', Record<never, never>, Record<never, never>>,
  }
}
